

name: Manual workflow


on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  contributer:
    runs-on: ubuntu-18.04
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.0.2
        with:
          image_size: 100
